django_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include("hello.urls")),
    path('sns/', include('sns.urls')),
]

hello/urls.py
from django.urls import path
from . import views
from .views import FriendList
from .views import FriendDetail

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:num>', views.index, name='index'),
    path('create', views.create, name='create'),
    path('edit/<int:num>', views.edit, name='edit'),
    path('delete/<int:num>', views.delete, name='delete'),
    path('list', FriendList.as_view()), 
    path('detail/<int:pk>', FriendDetail.as_view()), 
    path('find', views.find, name='find'), 
    path('check', views.check, name='check'),
    path('message/', views.message, name='message'),
    path('message/<int:page>', views.message, name='message'),
]

sns/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:page>', views.index, name='index'),
    path('groups', views.groups, name='groups'),
    path('add', views.add, name='add'),
    path('creategroup', views.creategroup, name='creategroup'),
    path('post', views.post, name='post'),
    path('share/<int:share_id>', views.share, name='share'),
    path('good/<int:good_id>', views.good, name='good'),
]

hello/models.py
import re
from django.db import models
from django.core.validators import ValidationError

def number_only(value):
    if (re.match(r'^[0-9]*$', value) == None):
        raise ValidationError(
            '%(value)s is not Number!', \
            params={'value': value},
        )


class Friend(models.Model):
    name = models.CharField(max_length=100, \
        validators=[number_only])
    mail = models.EmailField(max_length=200)
    gender = models.BooleanField()
    age = models.IntegerField()
    birthday = models.DateField()
     
    def __str__(self):
        return '<Friend:id=' + str(self.id) + ', ' + \
            self.name + '(' + str(self.age) + ')>'

class Message(models.Model):
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '<Message:id=' + str(self.id) + ', ' + \
            self.title + '(' + str(self.pub_date) + ')>'
    
    class Meta:
        ordering = ('pub_date',)

hello/forms.py
from django import forms
from.models import Friend, Message 

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['name','mail','gender','age','birthday']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'mail': forms.EmailInput(attrs={'class':'form-control'}),
            'age': forms.NumberInput(attrs={'class':'form-control'}),
            'birthday': forms.DateInput(attrs={'class':'form-control'}),
        }


class FindForm(forms.Form):
    find = forms.CharField(label='Find', required=False, \
        widget=forms.TextInput(attrs={'class':'form-control'}))

class CheckForm(forms.Form):
    str = forms.CharField(label='String', \
        widget=forms.TextInput(attrs={'class':'form-control'}))
    
    def clean(self):
        cleaned_data = super().clean()
        str = cleaned_data['str']
        if (str.lower().startswith('no')):
            raise forms.ValidationError('You input "NO"!')

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title','content','friend']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control form-control-sm'}),
            'content': forms.Textarea(attrs={'class':'form-control form-control-sm', 'rows':2}),
            'friend': forms.Select(attrs={'class':'form-control form-control-sm'}),
        }

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from .forms import FriendForm
from .forms import FindForm
from django.views.generic import ListView
from django.views.generic import DetailView
from django.db.models import Q
from django.db.models import Count,Sum,Avg,Min,Max
from .forms import CheckForm
from django.core.paginator import Paginator
from .models import Friend, Message
from .forms import FriendForm, MessageForm

class FriendList(ListView):
    model = Friend

class FriendDetail(DetailView):
    model = Friend

def index(request, num=1):
    data = Friend.objects.all()
    page = Paginator(data, 3)
    params = {
        'title': 'Hello',
        'message':'',
        'data': page.get_page(num),
    }
    return render(request, 'hello/index.html', params)

def create(request):
    if (request.method == 'POST'):
        obj = Friend()
        friend = FriendForm(request.POST, instance=obj)
        friend.save()
        return redirect(to='/hello')
    params = {
        'title': 'Hello',
        'form': FriendForm(),
    }
    return render(request, 'hello/create.html', params)

def edit(request, num):
    obj = Friend.objects.get(id=num)
    if (request.method == 'POST'):
        friend = FriendForm(request.POST, instance=obj)
        friend.save()
        return redirect(to='/hello')
    params = {
        'title': 'Hello',
        'id':num,
        'form': FriendForm(instance=obj),
    }
    return render(request, 'hello/edit.html', params)

def delete(request, num):
    friend = Friend.objects.get(id=num)
    if (request.method == 'POST'):
        friend.delete()
        return redirect(to='/hello')
    params = {
        'title': 'Hello',
        'id':num,
        'obj': friend,
    }
    return render(request, 'hello/delete.html', params)

def find(request):
    if (request.method == 'POST'):
        msg = request.POST['find']
        form = FindForm(request.POST)
        sql = 'select * from hello_friend'
        if (msg != ''):
            sql += ' where ' + msg
        data = Friend.objects.raw(sql)
        msg = sql
    else:
        msg = 'search words...'
        form = FindForm()
        data =Friend.objects.all()
    params = {
        'title': 'Hello',
        'message': msg,
        'form':form,
        'data':data,
    }
    return render(request, 'hello/find.html', params)

def check(request):
    params = {
        'title': 'Hello',
        'message':'check validation.',
        'form': FriendForm(),
    }
    if (request.method == 'POST'):
        obj = Friend()
        form = FriendForm(request.POST, instance=obj)
        params['form'] = form
        if (form.is_valid()):
            params['message'] = 'OK!'
        else:
            params['message'] = 'no good.'
    return render(request, 'hello/check.html', params)

def message(request, page=1):
    if (request.method == 'POST'):
        obj = Message()
        form = MessageForm(request.POST, instance=obj)
        form.save()
    data = Message.objects.all().reverse()
    paginator = Paginator(data, 5)
    params = {
        'title': 'Message',
        'form': MessageForm(),
        'data': paginator.get_page(page),
    }
    return render(request, 'hello/message.html', params)

hello/templates/hello/check.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <p>{{message|safe}}</p>
    <ol class="list-group mb-4">
    {% for item in form %}
    <li class="list-group-item py-2">{{ item.name }} ({{ item.value }})
        :{{ item.errors.as_text }}</li>
    {% endfor %}
    </ol>
    <form action="{% url 'check' %}" method="post">
        {% csrf_token %}
        <div class="form-group">名前{{ form.name }}</div>
        <div class="form-group">メール{{ form.mail }}</div>
        <div class="form-group">性別</th><td>{{ form.gender }}</div>
        <div class="form-group">年齢</th><td>{{ form.age }}</div>
        <div class="form-group">誕生日</th><td>{{ form.birthday }}</div>
        <div class="form-group">
            <input type="submit" value="click"
                class="btn btn-primary">
        </div>
    </form>
</body>
</html>

hello/templates/hello/create.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <form action="{% url 'create' %}" 
        method="post">
    {% csrf_token %}
        <table class="table">
        {{ form.as_table }}
            <tr><th><td>
                <input type="submit" value="click"
                    class="btn btn-primary mt-2">
            </td></th></tr>
        </table>
    </form>
</body>
</html>

hello/templates/hello/delete.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <p>※以下のレコードを削除します。</p>
    <table class="table">
        <tr><th>ID</th><td>{{obj.id}}</td></tr>
        <tr><th>Name</th><td>{{obj.name}}</td></tr>
        <tr><th>Gender</th><td>
        {% if obj.gender == False %}male{% endif %}
        {% if obj.gender == True %}female{% endif %}</td></tr>
        <tr><th>Email</th><td>{{obj.mail}}</td></tr>
        <tr><th>Age</th><td>{{obj.age}}</td></tr>
        <tr><th>Birth</th><td>{{obj.birthday}}</td></tr>
        <form action="{% url 'delete' id %}" method="post">
        {% csrf_token %}
        <tr><th></th><td>
            <input type="submit" value="click"
                class="btn btn-primary">
        </td></tr>
        </form>
    </table>
</body>
</html>

hello/templates/hello/edit.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <form action="{% url 'edit' id %}" 
        method="post">
    {% csrf_token %}
        <table class="table">
        {{ form.as_table }}
            <tr><th><td>
                <input type="submit" value="click"
                    class="btn btn-primary mt-2">
            </td></th></tr>
        </table>
    </form>
</body>
</html>

hello/templates/hello/find.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <p>{{message|safe}}</p>
    <form action="{% url 'find' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <tr><th></th><td>
        <input type="submit" value="click"
            class="btn btn-primary mt-2"></td></tr>
    </form>
    <hr>
    <table class="table">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>age</th>
            <th>mail</th>
            <th>birthday</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.name}}</td>
            <td>{{item.age}}</td>
            <td>{{item.mail}}</td>
            <td>{{item.birthday}}</td>
        <tr>
    {% endfor %}
    </table>
</body>
</html>

hello/templates/hello/friend_detail.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        Friends List</h1>
    <table class="table">
        <tr>
            <th>id</th>
            <th>{{object.id}}</th>
        </tr>
        <tr>
            <th>name</th>
            <td>{{object.name}}</td>
        </tr>
        <tr>
            <th>mail</th>
            <td>{{object.mail}}</td>
        </tr>
        <tr>
            <th>gender</th>
            <td>{{object.gender}}</td>
        </tr>
        <tr>
            <th>age</th>
            <td>{{object.age}}</td>
        </tr>
    </table>
</body>
</html>

hello/templates/hello/friend_list.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        Friends List</h1>
    <table class="table">
        <tr>
            <th>id</th>
            <th>name</th>
            <th></th>
        </tr>
    {% for item in object_list %}
        <tr>
            <th>{{item.id}}</th>
            <td>{{item.name}}</td>
            <td><a href="/hello/detail/{{item.id}}">detail</a></td>
        <tr>
    {% endfor %}
    </table>
</body>

</html>

hello/templates/hello/index.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <p>{{message|safe}}</p>
    <table class="table">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>age</th>
            <th>mail</th>
            <th>birthday</th>
            <th>Messages</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.name}}</td>
            <td>{{item.age}}</td>
            <td>{{item.mail}}</td>
            <td>{{item.birthday}}</td>
            <td><ul>
                {% for ob in item.message_set.all %}
                    <li>{{ob.title}}</li>
                {% endfor %}
                </ul></td>
            <tr>
    {% endfor %}
    </table>
    <ul class="pagination justify-content-center">
        {% if data.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'index' %}">
                &laquo; first</a>
        </li>
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'index' %}{{data.previous_page_number}}">
                &laquo; prev</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link">&laquo; first</a>
        </li>
        <li class="page-item">
            <a class="page-link">&laquo; prev</a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link">
            {{data.number}}/{{data.paginator.num_pages}}</a>
        </li>
        {% if data.has_next %}
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'index' %}{{data.next_page_number }}">
                next &raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'index' %}{{data.paginator.num_pages}}">
                last &raquo;</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link">next &raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link">last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</body>

hello/templates/hello/message.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    crossorigin="anonymous">
</head>
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
        <form action="{% url 'message' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="send"
            class="btn btn-primary">
    <div class="mt-5"></div>
    <table class="table">
        <tr>
            <th class="py-1">title</th>
            <th class="py-1">name</th>
            <th class="py-1">datetime</th>
        </tr>
    {% for item in data %}
        <tr>
            <td class="py-2">{{item.title}}</td>
            <td class="py-2">{{item.friend.name}}</td>
            <td class="py-2">{{item.pub_date}}</td>
        <tr>
    {% endfor %}
    </table>
    <ul class="pagination  justify-content-center">
        {% if data.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'message' %}">
                &laquo; first</a>
        </li>
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'message' %}{{data.previous_page_number}}">
                &laquo; prev</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link">&laquo; first</a>
        </li>
        <li class="page-item">
            <a class="page-link">&laquo; prev</a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link">
            {{data.number}}/{{data.paginator.num_pages}}</a>
        </li>
        {% if data.has_next %}
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'message' %}{{data.next_page_number }}">
                next &raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" 
            href="{% url 'message' %}{{data.paginator.num_pages}}">
                last &raquo;</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link">next &raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link">last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</body>
</html>